"""initial

Revision ID: c70b17367b6b
Revises: 
Create Date: 2024-11-29 21:35:39.734583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c70b17367b6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_washing_machines_id', table_name='washing_machines')
    op.drop_index('ix_washing_machines_name', table_name='washing_machines')
    op.drop_table('washing_machines')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('washing_machines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('installation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='washing_machines_pkey')
    )
    op.create_index('ix_washing_machines_name', 'washing_machines', ['name'], unique=False)
    op.create_index('ix_washing_machines_id', 'washing_machines', ['id'], unique=False)
    # ### end Alembic commands ###
